agent_policy:
  clip_param: 0.3
  entropy_coeff: 0.025
  entropy_coeff_schedule: null
  gamma: 0.8
  grad_clip: 10.0
  kl_coeff: 0.0
  kl_target: 0.01
  lambda: 0.9
  lr: 0.0003
  lr_schedule: null
  model:
    custom_model: ppo_linear
    custom_model_config: {}
    max_seq_len: 25
  use_gae: true
  vf_clip_param: 50.0
  vf_loss_coeff: 0.05
  vf_share_layers: false
env:
  env_name: toy
  env_width:
    SWEEP:
    - 4
  max_time: 5000
  n_agents: 2
  officer_weight: 3
  perturb:
    SWEEP:
    - 0.0
    - 0.1
    - 0.2
    - 0.3
    - 0.4
    - 0.5
    - 0.6
  random_perturb: true
  scale: 30
  seed:
    SWEEP:
    - 0
ermas:
  alpha_lr: 0.005
  epsilon: 0.001
  initial_lambda: 8.0
  metascale: 0.2
  parallel: true
  penalty: reptile
  use_ermas: false
general:
  ckpt_frequency_steps: 5000000
  cpus: 15
  episodes: 3000
  gpus: 0
  num_training_agents: -1
  remap: false
  restore_tf_weights_agents: null
  restore_tf_weights_planner: YOUR_EXPERIMENT_CKPTS/planner.tf.weights.global-step-latest
  train_planner: false
metadata:
  experiment: bimatrix/eval_oracle
  project: YourProjectName
  version: v1
planner_policy:
  clip_param: 0.3
  entropy_coeff: 0.1
  entropy_coeff_schedule: null
  gamma: 0.8
  grad_clip: 10.0
  kl_coeff: 0.0
  kl_target: 0.01
  lambda: 0.9
  lr: 0.0001
  lr_schedule: null
  model:
    custom_model: ppo_linear
    custom_model_config: {}
    max_seq_len: 25
  use_gae: true
  vf_clip_param: 50.0
  vf_loss_coeff: 0.05
  vf_share_layers: false
trainer:
  batch_mode: truncate_episodes
  env_config: null
  local_tf_session_args:
    inter_op_parallelism_threads: 2
    intra_op_parallelism_threads: 24
  metrics_smoothing_episodes: null
  multiagent: null
  no_done_at_end: false
  num_envs_per_worker: 4
  num_gpus: 0
  num_gpus_per_worker: 0
  num_sgd_iter: 1
  num_workers: 15
  observation_filter: NoFilter
  rollout_fragment_length: 200
  seed: null
  sgd_minibatch_size: 3000
  shuffle_sequences: true
  tf_session_args:
    allow_soft_placement: true
    device_count:
      CPU: null
      GPU: null
    gpu_options:
      allow_growth: true
    inter_op_parallelism_threads: 2
    intra_op_parallelism_threads: 24
    log_device_placement: false
  train_batch_size: 12000
